#!/bin/sh
# 配置 USB 共享网络：创建 usbwan 接口并加入防火墙 WAN 区域

# 如果 usbwan 接口不存在则创建
uci -q get network.usbwan >/dev/null || uci set network.usbwan=interface

uci set network.usbwan.proto='dhcp'
uci set network.usbwan.device='usb0'
uci set network.usbwan.hostname='OpenWrt-UFI103'

# 将 usbwan 加入防火墙 WAN 区域
WAN_ZONE=$(uci show firewall | sed -n "s/^firewall\.\(@zone\[[0-9]*\]\|cfg[0-9a-f]*\)\.name='wan'$/\1/p" | head -1)
[ -n "$WAN_ZONE" ] && uci add_list firewall.$WAN_ZONE.network='usbwan'

uci commit network
uci commit firewall
