#!/bin/sh
# 首次启动时启用 WiFi 并设置默认 AP

uci set wireless.radio0.disabled='0'
uci set wireless.radio0.htmode='HT40'
uci set wireless.radio0.channel='auto'
uci set wireless.radio0.country='CN'
uci set wireless.radio0.txpower='20'

uci set wireless.@wifi-iface[0].device='radio0'
uci set wireless.@wifi-iface[0].mode='ap'
uci set wireless.@wifi-iface[0].network='lan'
uci set wireless.@wifi-iface[0].ssid='OpenWrt-UFI103'
uci set wireless.@wifi-iface[0].encryption='psk2+ccmp'
uci set wireless.@wifi-iface[0].key='12345678'

uci commit wireless
